const labels = {
  addNewTopic: "Adicione um novo tópico na discussão",
  addPasswordTitle: "Crie uma senha",
  addPhoto: "Adicionar foto",
  addPlaceholderBody: "(Tudo o que você quiser dizer.)",
  addPlaceholderTitle: "Nós adoraríamos ouvir mais de você.",
  addYourComment: "Adicione o seu comentário",
  addYourReply: "Adicione a sua resposta",
  askMeLater: "Pergunte-me depois",
  backButton: "Voltar aos Comentários",
  body: "Body",
  cancel: "Cancelar",
  comment: "Comentar",
  comments: "Comentários",
  email: "Email",
  enter: "Entrar",
  formButton: "Enviar",
  imageEmpty: "Nenhuma imagem de perfil.",
  login: "Entrar",
  noComments: "Nenhum comentário ainda - faça o primeiro!",
  noReplies: "Nenhuma resposta ainda - faça a primeira!",
  ok: "OK",
  onboarding: {
    features: {
      title: "What to expect",
      theFeedTitle: "The Feed",
      theFeedBody: "Right now there’s just a very simple feed of posts from me talking about x and y.",
      joinDiscussionTitle: "Join the Discussion",
      joinDiscussionBody: "You can add your voice and join the discussion on each post on the feed in two ways.",
      topicsBody: "You can add a new topic with a ‘title’ and ‘body’. Like threads on a forum. This adds a new thread to the post which anyone can then reply to themselves.",
      repliesBody: "Each topic can have replies. Like comments on social media. This adds a response to an individual topic.",
      giveFeedbackTitle: "Give your feedback",
      giveFeedbackBody: "Unless you tell us what you think, we can’t build a great space for women to debate and feel safe. ...Bit more here.",
    },
  },
  noImageSelected: "Nenhuma imagem selecionada. Escolha uma e tente novamente.",
  password: "Senha",
  passwordSet: "Defina uma senha",
  passwordEmpty: "Campo de senha vazio.",
  passwordMismatch: "As senhas não são idênticas.",
  passwordMedium: "Senha quase forte o suficiente.",
  passwordRepeat: "Repita a senha",
  passwordRequest: "Uma senha forte, por favor.",
  passwordStrong: "Ótima senha!.",
  passwordWeak:
    "Senha muito fraca. Deve incluir:\n" +
    "- 1+ letra maiúscula\n- 1+ letra minúscula\n- 1+ número",
  permissionRequestPhotoLibraryBody:
    "Elpis requer acesso ao seu álbum de fotos para atualizar sua imagem de perfil.",
  permissionRequestPhotoLibraryTitle: "Acesso ao álbum de fotos",
  profilePictureRequest: "Por favor, deixe-nos ver o seu rosto.",
  reply: "Resposta",
  replies: "Respostas",
  select: "Selecionar",
  submit: "Submit",
  thankYouText:
    "Por favor, lembre-se de dar o máximo de feedback que puder.\r\r" +
    "Nós não poderemos construir algo incrível se você não nos disser o que pensa.",
  thankYouTitle: "Por favor, complete o seu perfil.",
  title: "Title",
  topics: "Tópicos",
  uploadingImage: "Carregando imagem",
  welcomeButton: "Próximo",
  welcomeTitle: "Bem vinda à Elpis, ",
  welcomeText: "Muitas palavras aqui. ",
};

export { labels };
